version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/core-api
      - REACT_APP_AUTH_URL=http://localhost:8000
    restart: unless-stopped
    
  # Optional: Include backend if you want full stack
  # backend:
  #   image: your-django-image:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DJANGO_DEBUG=False
  #     - DJANGO_SECRET_KEY=your-secret-key
  #   restart: unless-stopped

  # Optional: Reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - frontend
  #   restart: unless-stopped
